package com.kanban.data.impl.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Board generated by hbm2java
 */
@Entity
@Table(name = "board", schema = "public")
@XmlRootElement
public class Board implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8805193362571383030L;
	private int id;
	private String code;
	private String name;
	private int idtask;

	public Board() {
	}

	public Board(int id, String code, String name, int idtask) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.idtask = idtask;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "idtask", nullable = false)
	public int getIdtask() {
		return this.idtask;
	}

	public void setIdtask(int idtask) {
		this.idtask = idtask;
	}

}
