package com.kanban.data.impl.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task", schema = "public")
@XmlRootElement
public class Task implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9103028713192105524L;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", updatable = false, nullable = false)
	private long id;
	@Column(name = "code", nullable = false, length = 5)
	private String code;
	@Column(name = "description", nullable = false, length = 200)
	private String description;
	@Column(name = "duration", nullable = false)
	private double duration;
	@Column(name = "status", nullable = false, length = 20)
	private String status;
	@Column(name = "iduser", nullable = false)
	private long iduser;

	public Task() {
	}

	public Task(String code, String description, int duration, String status) {
		this.code = code;
		this.description = description;
		this.duration = duration;
		this.status = status;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getDuration() {
		return this.duration;
	}

	public void setDuration(double duration) {
		this.duration = duration;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public long getIduser() {
		return this.iduser;
	}

	public void setIduser(long iduser) {
		this.iduser = iduser;
	}

}
